### ISSUE TITLE
add strace support for new BTRFS_IOC_FS_INFO fields

### ISSUE THREAD

**Issue by morbidrsa** [btrfs/btrfs-todo#11]
Starting with kernel v5.9 the BTRFS_IOC_FS_INFO ioctl can also query the checksum type, checksum length, filesystem generation and metadata UUID.

This information is not yet parsed by strace, so it needs decoder support there as well.

**Comment by SahilKang** [comment]
Thanks for highlighting this so clearly; I've submitted a patch to the [strace mailing list](https://lists.strace.io/pipermail/strace-devel/2021-December/010809.html)

**Comment by SahilKang** [comment]
The patch got merged in https://github.com/strace/strace/commit/0966d2e3bb60ed1e0833f8c1b9b6619ea6bb783d so I think this issue is good to close
