### ISSUE TITLE
btrfs-convert is missing a dependancy on Arch Linux and Manjaro

### ISSUE THREAD

**Issue by unfa** [btrfs/btrfs-todo#31]
Attempting to run `btrfs-convert` on Manjaro or Arch Linux results in this error:

```
❯ btrfs-convert 
btrfs-convert: error while loading shared libraries: libreiserfscore.so.0: cannot open shared object file: No such file or directory
```

**Comment by jeffmahoney** [comment]
Wouldn't that be a packaging error on those distributions?

**Comment by unfa** [comment]
Installing `reiserfsprogs` fixes it, but that package is not marked as a dependancy (as I guess it should not be required to use Btrfs...)

**Comment by jeffmahoney** [comment]
It is required to convert a reiserfs to btrfs and is optional. Those distros chose to build it with that functionality enabled. Either way, this is not a btrfs project issue. It's an issue for the people responsible for packaging it on those distros.

**Comment by unfa** [comment]
Ok, thanks, I'll rise this issue with the Arch Linux people.
