### ISSUE TITLE
btrfsck uses one core only on multicore CPU

### ISSUE THREAD

**Issue by Windree** [btrfs/btrfs-todo#45]
btrfsck uses one core only on mulicore CPU that is bottleneck of init-csum-tree command

Command I run: `btrfsck /dev/sdg --init-csum-tree  --progress`

```
uname -a
Linux 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
btrfs --version
btrfs-progs v5.16.2
```

**Comment by kdave** [comment]
If you have a specific issue for btrfs-progs, please open it at https://github.com/kdave/btrfs-progs and also check if there isn't such issue opened alread. And there is: https://github.com/kdave/btrfs-progs/issues/460
