### ISSUE TITLE
FEATURE REQUEST: add option avoid looping question

### ISSUE THREAD

**Issue by FransM** [btrfs/btrfs-todo#52]
I needed to restore a large volume with btrfs restore
For several files it asked
We seem to be looping a lot on <filename>, do you want to keep going on ? (y/N/a): 
Now while entering a the question is suppressed for the current file, but it would be nice to have an option or an answer to suppress it totally.

Rationale: a large disk restore can take several hours and the user might not be at the screen all the time.

Workaround I used: yes | btrfs restore ....
but I feel it would be better to have this as an option (or as a possible answer the first time this question pops up.

**Comment by kdave** [comment]
Please open btrfs-progs issues at https://github.com/kdave/btrfs-progs
